### ISSUE TITLE
Docker build fails due to missing lwt_unix dependency

### ISSUE THREAD

**Issue by mwksl** [mwksl/snapcamel#1]
## Error Message
```
[5/5] RUN opam install . --deps-only -y &&     eval $(opam env) &&     dune build:
The following dependencies couldn't be met:
  - snapcamel -> lwt_unix
      unknown package

No solution found, exiting
```

## Steps to Reproduce
1. Run `docker build -t snapcamel .` in the project directory

## Possible Causes
- `lwt_unix` package is missing from the opam dependencies
- Incorrect package name for `lwt_unix` in the project's opam file

## TODO
- [ ] Check the project's opam file for the correct `lwt_unix` dependency
- [ ] Verify that `lwt_unix` is a valid opam package
- [ ] Update the Dockerfile or opam file as needed
- [ ] Rebuild the Docker image after making changes

## Additional Notes
- There's also a warning about a missing 'bug-reports' field in the package definition
